### PR TITLE
 bring kotlin project into executable shape and fixing the predefined tests

### PR DESCRIPTION
**Pull request by dnltsk**
1. `gradle test` failed with `:test NO-SOURCE`. This PR fixes the project structure make `gradle test` find some tests.
2. kotlin tests start with verse(int, int). I aligned them to the other languages: verse(int)

### CODE REVIEW

**Comment by dcarral** [comment]
Thank you very much @dnltsk 👍 

Wondering if we should take the opportunity to fully align the interface (e.g.: `#verse(int)` instead of `#verses(int)`, `#lyrics` returning the full song, etc.). We could also do it later in a separate PR too, like you prefer.

Plus, one unrelated question: @mklose recently improved (via PR #5) the Java setup by introducing [`gradlew`](https://docs.gradle.org/current/userguide/gradle_wrapper.html). Do you think it would make sense to use it here as well?

**Comment by dnltsk** [comment]
Hi, these are good points.
* gradlew is added now (verified with Mac)
* function names are now correct
* newlines are now the same as in java tests (last `\n` was missing in all expected verses)
* extended README with `gradlew` commands

**Comment by dnltsk** [comment]
* made `gradle eclipse` and `gradle idea` executable

**Comment by dcarral** [comment]
@dnltsk Unfortunately I'm having problems trying to run the test suite. This what I get as output from `./gradlew test`:

```
> FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':compileTestKotlin'.
> Compilation error. See log for more details
````

Running it with `--info` gives us more details:

```
Executing task ':compileTestKotlin' (up-to-date check took 0.0 secs) due to:
  Task.upToDateWhen is false.
All input files are considered out-of-date for incremental task ':compileTestKotlin'.
file or directory '/Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/java', not found
file or directory '/Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/java', not found
Using Kotlin incremental compilation
e: /Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/kotlin/BeerSongTest.kt: (10, 41): Unresolved reference: verse
e: /Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/kotlin/BeerSongTest.kt: (17, 41): Unresolved reference: verse
e: /Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/kotlin/BeerSongTest.kt: (24, 41): Unresolved reference: verse
e: /Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/kotlin/BeerSongTest.kt: (31, 41): Unresolved reference: verse
e: /Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/kotlin/BeerSongTest.kt: (38, 41): Unresolved reference: verse
e: /Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/kotlin/BeerSongTest.kt: (45, 41): Unresolved reference: verses
e: /Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/kotlin/BeerSongTest.kt: (52, 41): Unresolved reference: verses
e: /Users/danjourney/projects/99bottles-polyglot/kotlin/src/test/kotlin/BeerSongTest.kt: (360, 41): Unresolved reference: lyrics
[KOTLIN] deleting /Users/danjourney/projects/99bottles-polyglot/kotlin/build/kotlin-classes/test on error
[KOTLIN] deleting /Users/danjourney/projects/99bottles-polyglot/kotlin/build/kotlin-classes/test on error
:compileTestKotlin FAILED
```

Notice, however, that when trying to run the tests in [your submitted solution](https://github.com/dcarral/99bottles-solutions/pull/3), it works like a charm.

**Comment by dcarral** [comment]
Thank you very much Daniel, it works like a charm! 👍

**Pull request merged**
